# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:  |
            reticulate
            covr

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Install precommit framework
        run: precommit::install_precommit()
        shell: Rscript {0}

      - name: Install precommit framework
        run: precommit::use_precommit()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
